apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-config
  namespace: eventuate-tram-examples-customers-and-orders
data:
  connection_string: jdbc:sqlserver://mssql:1433;databaseName=eventuate
  sql_password: Eventuate123!
  sql_user: sa
